config/routes.rb
Lpt::Application.routes.draw do

  root :to => 'hosts#index'
  
  devise_for :users

  resources :versions,:constraints => { :id => /.*/ }

  resources :hosts, :constraints => { :id => /.*/ } do
    #this way we can scan a collection of hosts as well as a single host
    get 'scan', :on => :member 
    collection do
      get 'scan'
    end
    resources :installations
    resource :os
    resource :arch
  end

   
  resources :packages, :constraints => { :id => /.*/ } do
    resources :installations
    resources :versions
    resources :arches
  end
  
  resources :installations

  resources :jobs do
    collection do
      put 'clear'
      post 'reset_all'
    end
    #post 'reset_status', :on=> :member
  end
  
  resources :repos do
    get 'scan', :on => :member
    collection do
      get 'scan'
    end
  end
    
    
end

app/models/repo.rb
class Repo < ActiveRecord::Base
  has_many :hosts, :through => :sources
  has_many :sources
  has_many :installables
  has_many :packages, :through => :installables
  
  validates_uniqueness_of :url

  def self.import(hostname, import_params)
    host = Host.find_by_name(hostname)
    repos = import_params["yum_repos"].split(/^$/)

    repos.each do |repo|
      rep=repo.split("\n")
      rep_hash = {}

      rep.each do |r|
          next if !r.match(/Repo-/)
          line=r.split(":",2)
          #rep_hash[line[0].sub(/:$/,"").strip.chomp] = line[1..-1].join(" ").sub(/^:/,"").strip.chomp
          rep_hash[line[0].strip.chomp] = line[1..-1].join(" ").strip.chomp
      end

      enabled = 0      
      enabled = 1 if (rep_hash["Repo-status"] =~ /.*enabled.*/)
      type = ""

      if rep_hash.has_key?("Repo-metalink")
        found = Repo.find_or_create_by_url(rep_hash["Repo-metalink"])
        type = "Repo-metalink"
      elsif rep_hash.has_key?("Repo-mirrors")
        found = Repo.find_or_create_by_url(rep_hash["Repo-mirrors"])
        type = "Repo-mirrors"
      elsif rep_hash.has_key?("Repo-baseurl")
        found = Repo.find_or_create_by_url(rep_hash["Repo-baseurl"])
        type = "Repo-baseurl"
      end

      if rep_hash.has_key?("Repo-name")
        if found
          found.update_attributes(:name => rep_hash["Repo-name"], :repo_type => type)

          if source = Source.where(:host_id => host.id, :repo_id => found.id).first
            source.update_attributes(:enabled => enabled)
          else
            Source.create(:host_id => host.id, :repo_id => found.id, :enabled => enabled)
          end
          
        end
      end
      
    end # end repos.each
  end # end import method
  
  def to_s
    name
  end  

  def to_param
    name
  end
  
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    @search = Repo.search(params[:search])
    @repo = @search.all
  end

  def show
    @repo = Repo.find_by_name(params[:id])
    @sources = Source.select('*, count(host_id) as host_count').group(:host_id).where(:repo_id => @repo.id).joins(:repo)
    @search = Installable.where(:repo_id => @repo.id).includes(:package, :version, :arch).search(params[:search])
    @repo_installables = @search.all    
  end
  
  def scan(*repos)
    flash[:notice] = "Scanning repo..."
    @repo = Repo.find_by_name(params[:id])
    ScanRepos.create(:url => @repo.url)
    redirect_to repo_path(@repo)
  end

end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/index.html.erb
<h1>Listing Repositories</h1>

<%= form_for @search do |f| %>
  <%= f.label :name_contains %>
  <%= f.text_field :name_contains %><br />

  <%= f.submit "Search"%>
<% end -%><br />

<%= button_to "Scan Repos", scan_repos_path, :method => :get%>

<table class="list">
  <tr>
    <th><%= sort_link @search, :name, "Repository Name" %></th>
    <th>Repository type</th>
    <th>Url<th>
  </tr>
  <% @repo.each do |r| %>
    <tr class="<%= cycle("even", "odd") -%>">
      <td><%= link_to r.name, repo_path(r.name) %></td>
      <td><%= r.repo_type  %></td>
      <td><%= r.url  %></td>      
    </tr>
  <% end %>
</table>

app/views/repos/show.html.erb
<% title @repo %>

<div>
  <h3><%= "#{@repo}".capitalize %></h3>
  <%= button_to "Scan Repo", scan_repo_path(@repo), :method => :get%>
  <table>
    <tr>
      <th>Name</th>
      <th>Type</th>      
      <th>Url</th>      
      <th>Enabled</th>
      <th>Hosts</th>
    </tr>
    <% @sources.each do |s| -%>
      <tr class="<%= cycle("even", "odd") -%>">
        <td><%= s.name %></td>
        <td><%= s.repo_type %> </td>
        <td><%= s.url %> </td>
        <td><%= s.enabled %> </td>
        <td><%= s.host_count %> </td>                
      </tr>
    <% end -%>
  </table> 
</div>

<h3>Packages available on this repo.</h3>
<p>
  <%= form_tag repo_path(@repo), :method => "get" do %>
    Package name
    <%= text_field :search, :package_name_equals %>
    Version name
    <%= text_field :search, :version_name_equals %>
    Arch name
    <%= text_field :search, :arch_name_equals %>        
    <%= submit_tag "Search" %><br />
  <% end %>
</p>

<p>
  <table class="list">
    <tr>
      <th><%= sort_link @search, :package_name, "Package", :class => "package" %></th>
      <th><%= sort_link @search, :version_name, "Version", :class => "version" %></th>
      <th><%= sort_link @search, :arch_name, "Arch", :class => "arch" %></th>
     </tr>

    <% @repo_installables.each do |i| -%>
      <tr class="<%= cycle("even", "odd") -%>">
        <td><%= i.package %></td>
        <td><%= i.version %></td>
        <td><%= i.arch %></td>
      </tr>
    <% end -%>

  </table>
</p>