config/routes.rb
Lpt::Application.routes.draw do

  root :to => 'hosts#index'
  
  devise_for :users

  resources :versions,:constraints => { :id => /.*/ }

  resources :hosts, :constraints => { :id => /.*/ } do
    #this way we can scan a collection of hosts as well as a single host
    get 'scan', :on => :member 
    collection do
      get 'scan'
    end
    resources :installations
    resource :os
    resource :arch
  end

   
  resources :packages, :constraints => { :id => /.*/ } do
    resources :installations
    resources :versions
    resources :arches
  end
  
  resources :installations

  resources :jobs do
    collection do
      put 'clear'
      post 'reset_all'
    end
    #post 'reset_status', :on=> :member
  end
  
  resources :repos do
    get 'scan', :on => :member
    collection do
      get 'scan'
    end
  end
    
    
end

app/models/job.rb
class Job
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /jobs
  # GET /jobs.xml
  def index
    @jobs = Resque::Status.statuses()

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  def clear
    Resque::Status.clear
    flash[:notice] = "All jobs cleared."
    redirect_to jobs_path
  end

  def reset_all
    Resque.redis.flushdb
    flash[:notice] = "All jobs/queues/statuses reset."
    redirect_to jobs_path
  end
  
  #def reset_status
  #  hostname = ????
  #  Resque.redis.del(hostname)
  #  flash[:notice] = "Host #{hostnam} reset"
  #  redirect_to jobs_path
  #end

  def destroy
    Resque::Status.kill(params[:id])
    flash[:notice] = "Job sucessfully killed"
    redirect_to jobs_path
  end


end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<%= title "Jobs" %>
<h1>Listing jobs</h1>

<%= button_to "Clear jobs", {:action => "clear"}, {:method => :put} %>
<%= button_to "Reset jobs queues and statuses.", {:action => "reset_all"}, {:method => :post} %>

<div>
<p>
  <table class="list">
    <tr>
      <th>Uuid</th>
      <th>Name</th>
      <th>Status</th>
      <th>Time</th>
      <th>Message</th>
      <th>Kill<th>
    </tr>   
    <% @jobs.each do |j| %>
      <tr class="<%= cycle("even", "odd") -%>">
        <td><%= "#{j.uuid}" %></td>
        <td><%= "#{j.name}" %></td>
        <td><%= "#{j.status}" %></td>
        <td><%= "#{j.time}" %></td>
        <td><%= "#{j.message}" %></td>
        <% unless j.status == "completed" || j.status == "failed" || j.status == "killed" %>
          <td><%= button_to "Kill", {:action => "destroy", :id => j.uuid}, {:method => :delete} %></td>                       
        <% else %>
          <td></td>                                 
        <% end %>
      </tr>
    <% end %>
  </table>
</p>
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>