config/routes.rb
Lpt::Application.routes.draw do

  root :to => 'hosts#index'
  
  devise_for :users

  resources :versions,:constraints => { :id => /.*/ }

  resources :hosts, :constraints => { :id => /.*/ } do
    #this way we can scan a collection of hosts as well as a single host
    get 'scan', :on => :member 
    collection do
      get 'scan'
    end
    resources :installations
    resource :os
    resource :arch
  end

   
  resources :packages, :constraints => { :id => /.*/ } do
    resources :installations
    resources :versions
    resources :arches
  end
  
  resources :installations

  resources :jobs do
    collection do
      put 'clear'
      post 'reset_all'
    end
    #post 'reset_status', :on=> :member
  end
  
  resources :repos do
    get 'scan', :on => :member
    collection do
      get 'scan'
    end
  end
    
    
end

app/models/host.rb
class Host < ActiveRecord::Base
  has_many :installations, :dependent => :destroy
  # bug in dependent => destory, should be fixed in 2.3.6 #2251
  #after_destroy {|record| Installation.delete_all("host_id = #{record.id}")}
  has_many :packages, :through => :installations, :uniq => true
  belongs_to :os
  belongs_to :arch
  has_many :repos, :through => :sources
  has_many :sources

  #The :uniq option removes duplicates in Ruby code, not in the database query. 
  #If you have a large number of duplicates, it might be better to use the :select option to tell the 
  #database to remove duplicates using the DISTINCT keyword :select => "DISTINCT packages.*"

  validates_uniqueness_of :name

  def to_s
    name
  end

  def to_param
    name
  end

  def get_rpm_qa_md5(rpm_md5)
    if self.rpm_md5 == rpm_md5.strip.chomp
      return 1
    else
      return 0
    end
  end #end check_rpm_status

  def set_rpm_qa_md5(rpm_md5)
      self.update_attributes(:rpm_md5 => rpm_md5.strip.chomp)
  end #end check_rpm_status

  def increment_failed_scans()
    self.increment!(:failed_scans)
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_filter :find_by_name, :authenticate_user!

  include ActionView::Helpers::TextHelper

  respond_to :html,:json,:yaml
  def index
    @search = Host.includes(:arch, :os).search(params[:search])
    @hosts = @search.all
    respond_with(@hosts)
  end

  def show
    @host = Host.find_by_name(params[:id])
    @arch_split = Installation.select('arches.name, count(*) as count').joins(:arch).where(:host_id => @host.id).group(:arch_id).all
    @repos = Source.where(:host_id => @host.id).joins(:repo).where(:enabled => true).all
    @search = Installation.where(:host_id => @host.id, :currently_installed => 1).includes(:host, :package, :version, :arch).search(params[:search])
    @host_installations = @search.all
    #@host = Host.find_by_name(params[:id])                         
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => {:host_information => @host.to_json(:only => [:name, :running_kernel]), 
                                      :installation => @host_installations.to_json(:only => :installed_on, :include => {:package => {:only => :name},
                                                                                                                        :version => {:only => :name},
                                                                                                                        :arch => {:only => :name}}) } }
    end       
  end

  def edit
    @host = Host.find_by_name(params[:id])
  end

  def new
    @host = Host.new
  end

  def create
    @host = Host.new(params[:host])
    if @host.save
      scan(@host)
    else
      render :action => "new"
    end
  end

  def update
    @host = Host.find_by_name(params[:id])

    if @host.update_attributes(params[:host])
      redirect_to @host
      flash[:notice] = "Host was successfully updated."
    end
  end  

  def destroy
    if @host.destroy
      respond_to do |format|
        format.html { notice "Successfully destroyed host." }
        format.json { render :json => @host, :status => :ok and return }
      end
    else
      respond_to do |format|
        format.html { error @host.errors.full_messages.join("<br/>") }
        format.json { render :json => @host.errors, :status => :unprocessable_entity and return }
      end
    end
    redirect_to hosts_url
  end

  def scan(*host)
    if host.empty?
      if params[:id]
        host = Host.find_by_name(params[:id]) 
        ScanHosts.create(:hostname => host.name)
        flash[:notice] = "#{host.name} is being scanned for packages. Please refresh the page to view them."
        redirect_to host        
      elsif params[:host_ids]
        ids = params[:host_ids]
        ids.shift if ids[0] == "All"
        ids.each do |id|
          host = Host.find(id) 
          ScanHosts.create(:hostname => host.name)          
        end
        flash[:notice] = "#{pluralize(ids.size, 'Host is', 'Hosts are')} being scanned for packages."
        redirect_to hosts_path        
      end
    else
      host.each do |h|
        ScanHosts.create(:hostname => h.name)
      end
      flash[:notice] = "#{pluralize(host.size, 'Host is', 'Hosts are')} being scanned for packages. Please visit the hosts page to view them."
      redirect_to hosts_path
    end
  end
  
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<%= form_for(@host) do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hosts/_list.html.erb
<div>
  <p>
  <% if hosts.size > 0 -%>
    <%= form_for @search do |f| %>
      <%= f.label "Host name" %>
      <%= f.text_field :name_contains %>
      <%= f.submit "Search"%>
    <% end -%>
  <% end -%>
  </p>
</div>

<div>
  <p>
  <%= form_tag scan_hosts_path, :method => :get, :id => "select" do %>
    <%= submit_tag "Scan selected hosts" %>
    <table class="list">
      <tr>
        <th><input type="checkbox" name="host_ids[]" value="All" onClick="$$('#select input.check').each(function(box){box.checked=!box.checked})">All</th>
        <th><%= sort_link @search, :name %></th>
        <th><%= sort_link @search, :arch_name, "Arch", :class => "arch" %></th>
        <th><%= sort_link @search, :os_name, "Os", :class => "os" %></th>
      </tr>
      <% hosts.each do |host| -%>
        <tr class="<%= cycle("even", "odd") -%>">
          <td><%= check_box_tag "host_ids[]", host.id, false, :class => "check" %></td>
          <td><%=h link_to host.name, host %></td>
          <td><%=h host.arch %></td>
          <td><%=h host.os %></td>
        </tr>
      <% end -%>
    </table>
  <% end %>  
  </p>
</div>

app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Show', @host %> |
<%= link_to 'Back', hosts_path %>

app/views/hosts/index.html.erb
<%= title "Hosts" %>
<p>
  <span class="top">
    <%= link_to 'Create New Host', new_host_path %>
  </span>
</p>
<%= render 'list', :hosts => @hosts, :header => "Hosts"  %>

app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', hosts_path %>

app/views/hosts/show.html.erb
<%= title @host.name %>

<div>
  <h3>Host Information.</h3>
  <table>
    <tr class="<%= cycle("even", "odd") -%>">
      <td>Host Name</td>  
      <td><%= @host.name %></td>
    </tr>      
    <tr class="<%= cycle("even", "odd") -%>">
      <td>Operating System</td>  
      <td><%= @host.os %></td>
    </tr>      
    <tr class="<%= cycle("even", "odd") -%>">      
      <td>Running Kernel</td>  
      <td><%= @host.running_kernel %></td>
    </tr>
  </table>  
  <%= link_to 'Scan host', scan_host_path(@host), {:method => :get} %> <%= button_to 'Edit host', edit_host_path(@host), {:method => :get} %>
</div>

<div>
<p>
  <b>Package split by architecture.</b><br />
  <table>
    <tr>
      <th>Architecture</th>
      <th>Number of packages</th>
    </tr>   
    <% @arch_split.each do |i| %>
      <tr class="<%= cycle("even", "odd") -%>">
        <td><%= "#{i.name}:" %></td>
        <td><%= link_to "#{i.count}", :controller => "hosts", :action => "show", :search => {"arch_name_equals" => "#{i.name}"} %></td>
      </tr>
    <% end %>
  </table>
</p>
</div>

<div>
<p>
  <b>Repositories currently enabled.</b><br />
  <table>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Url</th>
    </tr>  
    <% @repos.each do |r| %>
      <tr class="<%= cycle("even", "odd") -%>">    
        <td><%= link_to("#{r.repo.name}", :controller => "repos", :action => "show", :id => r.repo.name) %></td>
        <td><%= "#{r.repo.repo_type}" %></td>
        <td><%= url_for("#{r.repo.url}") %></td>
      </tr>
    <% end %>
  </table>
</p>
</div>   

<h3>Packages installed on this host.</h3>

<p>
  <%= form_tag host_path(@host), :method => "get" do %>
    Package name
    <%= text_field :search, :package_name_equals %>
    Version name
    <%= text_field :search, :version_name_equals %>
    Arch name
    <%= text_field :search, :arch_name_equals %>        
    <%= submit_tag "Search" %><br />
  <% end %>
</p>

<p>
  <table class="list">
    <tr>
      <th><%= sort_link @search, :package_name, "Package", :class => "package" %></th>
      <th><%= sort_link @search, :version_name, "Version", :class => "version" %></th>
      <th><%= sort_link @search, :arch_name, "Arch", :class => "arch" %></th>
      <th><%= sort_link @search, :installed_on, "Install Date", :class => "installation" %></th>
     </tr>

    <%= render @host_installations %>

  </table>
</p>      