config/routes.rb
Lpt::Application.routes.draw do

  root :to => 'hosts#index'
  
  devise_for :users

  resources :versions,:constraints => { :id => /.*/ }

  resources :hosts, :constraints => { :id => /.*/ } do
    #this way we can scan a collection of hosts as well as a single host
    get 'scan', :on => :member 
    collection do
      get 'scan'
    end
    resources :installations
    resource :os
    resource :arch
  end

   
  resources :packages, :constraints => { :id => /.*/ } do
    resources :installations
    resources :versions
    resources :arches
  end
  
  resources :installations

  resources :jobs do
    collection do
      put 'clear'
      post 'reset_all'
    end
    #post 'reset_status', :on=> :member
  end
  
  resources :repos do
    get 'scan', :on => :member
    collection do
      get 'scan'
    end
  end
    
    
end

app/models/version.rb
class Version < ActiveRecord::Base

  has_many :installations, :dependent => :destroy
  has_many :packages, :through => :installations
  has_many :installables
  has_many :packages, :through => :installables  
  has_many :hosts, :through => :installations, :uniq => true

  validates_uniqueness_of :name
  validates_format_of :name, :with => /\A(\S+\s?)+\Z/, :message => "can't be blank or contain trailing white space"
  
  def to_s
    name
  end  

  def to_param
    name
  end


end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_filter :find_by_name

  respond_to :html,:json,:yaml

  def index
    @search = Version.search(params[:search])
    @versions = @search.all
    respond_with(@versions)
  end

  def show
    #@version = Version.where(:id => params[:id])
    @version = Version.find_by_name(params[:id])
    if @version.nil?
      begin
        raise ActiveRecord::RecordNotFound
      rescue ActiveRecord::RecordNotFound
        flash[:notice] = "The version you selected doesnt exist!"
        redirect_to versions_path    
      end
    else
      @search = Installation.select('name, count(host_id) as host_count').joins(:version).where(:version_id => @version.id).group('name')
      @installs = @search.all
      respond_to do |format|
        format.html # show.html.erb
        format.json  { 
          @search = Installation.select("hosts.name as #{@version.name}").joins(:version,:host,:version).where(:version_id => @version.id, :version_id => @version.version_ids)
          @installs = @search.all
          render :json => @installs
        }
      end    
    end          
  end

  def new
    @version = version.new
  end

  def create
    @version = Persion.new(params[:version])
    if @version.save
      flash[:notice] = "version successfully created."
      redirect_to @version
    else
      render :action => 'new'
    end
  end
#
#  # PUT /versions/1
#  # PUT /versions/1.xml
#  def update
#    @version = Version.find(params[:id])
#
#    respond_to do |format|
#      if @version.update_attributes(params[:version])
#        format.html { redirect_to(@version, :notice => 'Version was successfully updated.') }
#        format.xml  { head :ok }
#      else
#        format.html { render :action => "edit" }
#        format.xml  { render :xml => @version.errors, :status => :unprocessable_entity }
#      end
#    end
#  end
#
#  # DELETE /versions/1
#  # DELETE /versions/1.xml
#  def destroy
#    @version = Version.find(params[:id])
#    @version.destroy
#
#    respond_to do |format|
#      format.html { redirect_to(versions_url) }
#      format.xml  { head :ok }
#    end
#  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/index.html.erb
<h1>Listing Versions</h1>

<%= form_for @search do |f| %>
  <%= f.label :name_equals %>
  <%= f.text_field :name_equals %><br />
  <h6> OR </h6>
  <%= f.label :name_contains %>
  <%= f.text_field :name_contains %><br />
  <%= f.submit "Search"%>
<% end -%>

<table class="list">
  <tr>
    <th><%= sort_link @search, :name, "Version Name" %></th>
    <th>Packages<th>
  </tr>
  <% @versions.each do |v| %>
    <tr class="<%= cycle("even", "odd") -%>">
      <td><%= link_to v.name, version_path(v.name) %></td>
      <td><%= "TODO"  %></td>
    </tr>
  <% end %>
</table>

app/views/versions/show.html.erb
<p>
  <strong>Version Name:</strong>
  <%=h @version.name %>
</p>
<table class="list">
  <tr>
    <th>Version</th>
    <th>Packages</th>
  </tr>
  <% @installs.each do |i| -%>
    <tr class="<%= cycle("even", "odd") -%>">
      <td><%= link_to i.name, version_path(i.name)  %></td>
      <td><%= "#{i.host_count}" %> </td>
    </tr>
  <% end -%>
</table>

<p>
  <%= link_to "View All versions", versions_path %>
</p>